---
title: "BCB420 Assignment 1"
output: html_notebook
---
Set up and download dataset:
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!requireNamespace("GEOmetadb", quietly = TRUE))
    BiocManager::install("GEOmetadb")
if (!requireNamespace("edgeR", quietly = TRUE))
    BiocManager::install("edgeR")
suppressPackageStartupMessages({
  library(tidyverse)
library(edgeR)
library(org.Hs.eg.db)
library(GEOmetadb)
})

if(!file.exists('GEOmetadb.sqlite')) getSQLiteFile()
con <- dbConnect(SQLite(),'GEOmetadb.sqlite')
geo_tables <- dbListTables(con)
geo_tables

sql <- paste("SELECT DISTINCT gse.title,gse.gse, gpl.title,",
             " gse.submission_date,",
             " gse.supplementary_file",
             "FROM",
             "  gse JOIN gse_gpl ON gse_gpl.gse=gse.gse",
             "  JOIN gpl ON gse_gpl.gpl=gpl.gpl",
             "WHERE",
             "  gse.submission_date > '2017-01-01' AND",
             "  gpl.organism LIKE '%Homo sapiens%' AND",
             "  gpl.technology LIKE '%high-throughput seq%' ",
             sep=" ")
rs <- dbGetQuery(con,sql)
dim(rs)
ds <- "GSE119315"
# Download data
sfiles = getGEOSuppFiles(ds)

# read in data
dirname = rownames(sfiles)
dirname <- strsplit(dirname[1], split=".tar")[[1]][[1]]
files <- system(paste("ls", dirname, sep=" "), intern=TRUE)
files<- paste(dirname, files, sep="/")

data <- files %>%
  map(read.delim) %>%
  bind_cols
print(data)
# remove duplicate gene id columns
data <- data %>% 
  select(c(ends_with("...1"), starts_with("d"))) %>%
  rename(gene_id = gene_id...1)

```

Map gene ids to HUGO gene symbols and filter:
```{r}

data$gene_id <- sapply(strsplit(data$gene_id,"\\."), `[`, 1)
ens2symbol <- AnnotationDbi::select(org.Hs.eg.db,
                                    key=data$gene_id, 
                                    columns="SYMBOL",
                                    keytype="ENSEMBL")
ens2symbol <- as_tibble(ens2symbol)
ens2symbol
res <- inner_join(data, ens2symbol, by=c("gene_id"="ENSEMBL"))
keep <- res %>% 
  select(starts_with("d"))%>%
  cpm() %>%
  rowSums(.>1) >= 8
resFilt <- res[keep,]
# create groups matrix:
g <- unlist(strsplit(colnames(res)[2:9], split="_"))
days <- sapply(g, `[`, 1)
days <- sapply(strsplit(days, split="d"), `[`, 2)
sample <- sapply(g, `[`, 2)
expDesign <- (cbind(as.numeric(days), as.numeric(sample)))
expDesign <- as.data.frame(expDesign)
rownames(expDesign) <- colnames(res)[2:9]
colnames(expDesign) <- c("day", "replicate")
# normalization:
d <- DGEList(as.matrix(res[,2:9]), group=expDesign$day)
dnorm <- calcNormFactors(d)
```
Try mapping with this: https://support.bioconductor.org/p/87454/
and also read paper to see how authors mapped it
```{r}


```

